name: network_bound_resource
description: A package to handle offline http request easily
version: 1.0.0
homepage: https://github.com/CamiiloAF/network_bound_resource

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  sembast: ^3.3.1
  path: ^1.8.2
  path_provider: ^2.0.11
  connectivity_plus: ^3.0.2
  dio: ^4.0.6

dev_dependencies:
  lints: ^2.0.1
  test: ^1.23.1
  dart_code_metrics: ^5.1.0
  mocktail: ^0.3.0
